In [23]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

data = pd.read_csv("./datasets/train.csv")
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [24]:
Y_train

array([1, 1, 5, ..., 1, 6, 1], shape=(41000,))

In [25]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(Z, 0)

def softmax(Z):
    A = np.exp(Z) / sum(np.exp(Z))
    return A
    
def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def ReLU_deriv(Z):
    return Z > 0

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * ReLU_deriv(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1    
    W2 = W2 - alpha * dW2  
    b2 = b2 - alpha * db2    
    return W1, b1, W2, b2

In [26]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, alpha, iterations):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = backward_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print(get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [27]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[9 9 9 ... 9 0 9] [1 1 5 ... 1 6 1]
0.08158536585365854
Iteration:  10
[0 7 8 ... 7 0 9] [1 1 5 ... 1 6 1]
0.11109756097560976
Iteration:  20
[7 7 8 ... 7 6 8] [1 1 5 ... 1 6 1]
0.12392682926829268
Iteration:  30
[8 7 8 ... 7 6 8] [1 1 5 ... 1 6 1]
0.1351219512195122
Iteration:  40
[8 7 8 ... 2 0 8] [1 1 5 ... 1 6 1]
0.15104878048780487
Iteration:  50
[8 8 1 ... 2 6 1] [1 1 5 ... 1 6 1]
0.23139024390243904
Iteration:  60
[1 8 1 ... 1 4 1] [1 1 5 ... 1 6 1]
0.2788048780487805
Iteration:  70
[1 1 1 ... 1 4 1] [1 1 5 ... 1 6 1]
0.3040731707317073
Iteration:  80
[1 1 1 ... 1 4 1] [1 1 5 ... 1 6 1]
0.32421951219512196
Iteration:  90
[1 1 1 ... 1 4 1] [1 1 5 ... 1 6 1]
0.3443414634146341
Iteration:  100
[1 1 1 ... 1 4 1] [1 1 5 ... 1 6 1]
0.36478048780487804
Iteration:  110
[1 1 1 ... 1 4 1] [1 1 5 ... 1 6 1]
0.3824390243902439
Iteration:  120
[1 1 1 ... 1 4 1] [1 1 5 ... 1 6 1]
0.39958536585365856
Iteration:  130
[1 1 1 ... 1 9 1] [1 1 5 ... 1 6 1]
0.41778048780487803
Iteratio

In [28]:
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_prop(W1, b1, W2, b2, X)
    predictions = get_predictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    current_image = X_train[:, index, None]
    prediction = make_predictions(X_train[:, index, None], W1, b1, W2, b2)
    label = Y_train[index]
    print("Prediction: ", prediction)
    print("Label: ", label)
    
    current_image = current_image.reshape((28, 28)) * 255
    plt.gray()
    plt.imshow(current_image, interpolation='nearest')
    plt.show()